.\" Manpage for rssreader.
.\" Problems pleases contact xy6g11@ecs.soton.ac.uk.
.TH man 1 "22th Februrary 2012" "1.0.0" "rssreader manpage"
.SH NAME
rssreader \- read rss feeds from bbc.co.uk
.SH SYNOPSIS
xy6g11
.SH DESCRIPTION
This is a free program that used to retrieve the rss feeds from bbc.co.uk.

.SH OPTIONS
No options allowed.
.SH SEE ALSO

.SH BUGS
Non
.SH AUTHOR
Xiaojian Yi (xy6g11@ecs.soton.ac.uk)
